kafka:
  replicas: 3
  requests:
    memory: 16Gi
    cpu: "2"
  limits:
    memory: 16Gi
    cpu: "4"
  jvmOptions:
    xms: 8192m
    xmx: 8192m
  storage:
    size: 50G
  config:
    offsets:
      topic:
        replication:
          factor: 3
    transaction:
      state:
        log:
          replication:
            factor: 3
          min:
            isr: 2
    default:
      replication:
        factor: 3
    min:
      insync:
        replicas: 2

zookeeper:
  replicas: 3
  resources:
    requests:
      memory: 4Gi
      cpu: "2"
    limits:
      memory: 4Gi
      cpu: "2"
    jvmOptions:
      xms: 4096m
      xmx: 4096m
  storage:
    size: 10Gi

entityOperator:
  topicOperator:
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 512Mi
        cpu: "1"
  userOperator:
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 512Mi
        cpu: "1"

bridge:
  replicas: 3
  ingress:
    name: "kafka-internal-ingress"
    annotations:
      kubernetes.io/ingress.class: "gce-internal"
  rules:
    host: kafka.bridge.dev.io

topics:
  keyMouseEvent:
    partitions: 3
    replicas: 3