kafka:
  replicas: 1
  requests:
    memory: 2Gi
    cpu: "1"
  limits:
    memory: 2Gi
    cpu: "1"
  jvmOptions:
    xms: 2048m
    xmx: 2048m
  storage:
    size: 10G
  config:
    offsets:
      topic:
        replication:
          factor: 1
    transaction:
      state:
        log:
          replication:
            factor: 1
          min:
            isr: 1
    default:
      replication:
        factor: 1
    min:
      insync:
        replicas: 1

zookeeper:
  replicas: 1
  resources:
    requests:
      memory: 512Mi
      cpu: "250m"
    limits:
      memory: 1Gi
      cpu: "500m"
    jvmOptions:
      xms: 512m
      xmx: 512m
  storage:
    size: 1Gi

entityOperator:
  topicOperator:
    resources:
      requests:
        memory: 512Mi
        cpu: "250m"
      limits:
        memory: 512Mi
        cpu: "250m"
  userOperator:
    resources:
      requests:
        memory: 512Mi
        cpu: "250m"
      limits:
        memory: 512Mi
        cpu: "250m"

bridge:
  replicas: 1
  rules:
    host: localhost

topics:
  keyMouseEvent:
    partitions: 1
    replicas: 1
  test:
    name: test
    partitions: 1
    replicas: 1

